config/routes.rb
Bandrockr::Application.routes.draw do
  get "admin" => "admin#index"
  resources :gigs

  resources :photos

  resources :tracks

  resources :albums

  resources :links

  resources :members

  resources :band_profiles

  root :to => "home#index"
  resources :users, :only => [:index, :show, :edit, :update ]
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/album.rb
class Album < ActiveRecord::Base
	has_many :tracks
	belongs_to :band_profile
end

app/models/band_profile.rb
class BandProfile < ActiveRecord::Base
	belongs_to :user
	has_many :albums
	has_many :gigs
	has_many :members
	has_many :photos
	has_many :links

end

app/models/gig.rb
class Gig < ActiveRecord::Base
	belongs_to :band_profile
end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :band_profile
  belongs_to :member
end

app/models/member.rb
class Member < ActiveRecord::Base
	has_many :links
	belongs_to :band_profile
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	belongs_to :band_profile
	mount_uploader :image, BandPhotoUploader
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/track.rb
class Track < ActiveRecord::Base
  belongs_to :album
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  has_one :band_profile

  validates_presence_of :name

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      if auth['info']
         user.name = auth['info']['name'] || ""
         user.email = auth['info']['email'] || ""
      end
    end
  end

end

app/controllers/gigs_controller.rb
class GigsController < ApplicationController
  before_action :set_gig, only: [:show, :edit, :update, :destroy]

  # GET /gigs
  # GET /gigs.json
  def index
    @gigs = Gig.all
  end

  # GET /gigs/1
  # GET /gigs/1.json
  def show
  end

  # GET /gigs/new
  def new
    @gig = Gig.new
  end

  # GET /gigs/1/edit
  def edit
  end

  # POST /gigs
  # POST /gigs.json
  def create
    @gig = Gig.new(gig_params)
    @gig.band_profile_id = current_user.band_profile.id

    respond_to do |format|
      if @gig.save
        format.html { redirect_to admin_path, notice: 'Gig was successfully created.' }
        format.json { render action: 'show', status: :created, location: @gig }
      else
        format.html { render action: 'new' }
        format.json { render json: @gig.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gigs/1
  # PATCH/PUT /gigs/1.json
  def update
    respond_to do |format|
      if @gig.update(gig_params)
        format.html { redirect_to admin_path, notice: 'Gig was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @gig.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gigs/1
  # DELETE /gigs/1.json
  def destroy
    @gig.destroy
    respond_to do |format|
      format.html { redirect_to gigs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gig
      @gig = Gig.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gig_params
      params.require(:gig).permit(:title, :date, :start_time, :finish_time, :location, :street_address, :suburb, :tickets_url)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
	def ends_in_s?(band_profile_name)
		if band_profile_name.last != 's'
			's'
		end
	end
	
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gigs_helper.rb
module GigsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/admin/index.html.erb
<h1>MY BAND PROFILE PAGE</h1>

<% if !current_user.band_profile %>
	<div class="alert alert-warning">
	<h4>You don't have a profile yet! Create your band profile now!</h4>
	<br>
		<%= link_to "Create Your Profile", new_band_profile_path, class: 'btn btn-success' %>
	</div>
<% else %>
	<div class="well">
		<h2><%= @band_profile.name %></h2>
		<p class="lead"><%= @band_profile.info %></p>
	</div>

	<h3><%= @band_profile.name %>'<%= ends_in_s?(@band_profile.name)%> Gigs</h3>
	<% if @gigs %>
		<% @gigs.each do |gig| %>
			<div class="well">
				<strong><%= gig.title %></strong>
				<br>
				<p>Location: <%= gig.location %></p>
				<p>Date: <%= gig.date.to_date %></p>
				<p>Kicks Off: <%= gig.start_time.to_time %> </p>
				<%= link_to "Edit", edit_gig_path(gig) %>
			</div>
		<% end %>
		<% end %>
<hr>
<%= link_to "Add Gig", new_gig_path, class: 'btn btn-success' %>
<hr>
<br>
<h3><%= @band_profile.name %>'<% if @band_profile.name.last != 's' %>s<% end %> Photos</h3>
<% if @photos %>
	<%= link_to "Photo Gallery", photos_path(band_profile: @band_profile), class: 'btn btn-info' %>
<% end %>

<%= link_to "Add Photos", new_photo_path, class: 'btn btn-success' %>
<hr>

<% end %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Twitter Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Home", root_path, :class => 'navbar-brand' %>
<ul class="nav navbar-nav">
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Logout', signout_path %>
    </li>
  <% else %>
    <li>
    <%= link_to 'Login', signin_path %>
    </li>
  <% end %>
  <% if user_signed_in? %>
    <% if current_user.has_role? :admin %>
      <li>
      <%= link_to 'Admin', admin_path %>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Bandrockr" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Bandrockr" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%# application layout styled for Twitter Bootstrap 3.0 %>
    <header>
      <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
          <div class="collapse navbar-collapse">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </nav>
    </header>
    <main role="main">
      <div class="container">
         <div class="row">
           <div class="col-md-12">
             <%= render 'layouts/messages' %>
             <%= yield %>
           </div>
         </div>
      </div>
    </main>
  </body>
</html>